"""Ajout champ prolongations

Revision ID: 830010080900
Revises: e3874a3e79a2
Create Date: 2025-11-09 12:32:15.378154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830010080900'
down_revision = 'e3874a3e79a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amende', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prolongations', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'adherent', ['adherent_id'], ['id'])
        batch_op.create_foreign_key(None, 'livre', ['livre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prolongations')
        batch_op.drop_column('amende')

    # ### end Alembic commands ###
