"""Ajout résumé et PDF

Revision ID: e3874a3e79a2
Revises: 
Create Date: 2025-11-09 12:21:22.338355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3874a3e79a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilan')
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'adherent', ['adherent_id'], ['id'])
        batch_op.create_foreign_key(None, 'livre', ['livre_id'], ['id'])

    with op.batch_alter_table('livre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_pdf', sa.String(length=255), nullable=True))
        batch_op.drop_column('contenu')
        batch_op.drop_column('fichier_numerique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('livre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fichier_numerique', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contenu', mysql.TEXT(), nullable=True))
        batch_op.drop_column('contenu_pdf')

    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('bilan',
    sa.Column('nom', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('nom'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
